### ISSUE TITLE
some requests.

### ISSUE THREAD

**Issue by Gabbyr** [openscore/score#2]
score seems very interesting to be used in several use cases. in order to ease the use, I would like to ask a few requests to make it easier to work with : 

1.	add compile command to CLI – so one can have a “dry run” on the yaml flow file.
2.	visual EP tool for slang, a way to see your flow from a slang file. 
3.	Parallel feature is important. ant like structure is a good example.
4.	docs for content (Java + Yaml). you are lacking content docs, both on the Yaml flows/operations and on Java actions.

**Comment by oritstone** [comment]
Hi @Gabbyr ,

Thanks for your very constructive feedback.

We just released our 1st public version, and are currently working on the next version.

As part of our road-map, we are definitely  considering to have a visual tool for viewing flows. 
Parallel capabilities are naturally part of our road-map as well.
Regarding our Slang content, we already started working on improving our documentation and validation.

Thanks again for your feedback.

**Comment by meirwah** [comment]
we can close this right ?

**Comment by orius123** [comment]
if it is added to some backlog..

**Comment by meshipeer** [comment]
#1 - covered bu the -inputs command
#2 + #3 - added to our backlog
#4 - we added best practices and improve our content documentation
