### ISSUE TITLE
object mapper in worker mbean

### ISSUE THREAD

**Issue by orius123** [openscore/score#22]
@meirwah why do we need objectmapper in workermbean? And why do we initialize it in post construct. It has impact on score load time.

**Comment by meirwah** [comment]
it seems to be used only in the method "showWorkers" (Returns a list of all registered workers), i do not think this feature/method is really used in OO, so i think we can removed it...
We need to validate this of course...

how big in the impact on score load time?

**Comment by orius123** [comment]
Depends.. but it can take up to a whole second because it scans the classpath for some annotations. We can work around it but if it is not required, I say we remove it / replace with gson / move init into the show workers method.

**Comment by meirwah** [comment]
:+1:
