### ISSUE TITLE
need to remove nexus url - from all projects!!

### ISSUE THREAD

**Issue by meshipeer** [openscore/score#4]
Score-content + slang + score : pom.xml  contains:
 
<distributionManagement>
        <repository>
            <id>nexus-repository</id>
            <name>nexus repository</name>
            <url>http://mydphdb0166.hpswlabs.adapps.hp.com:8081/nexus/content/repositories/releases/</url>
        </repository>
        <snapshotRepository>
            <id>nexus-snapshot-repository</id>
            <name>nexus snapshots repository</name>
            <url>http://mydphdb0166.hpswlabs.adapps.hp.com:8081/nexus/content/repositories/snapshots/</url>
        </snapshotRepository>
    </distributionManagement>
<url>http://mydphdb0166.hpswlabs.adapps.hp.com:8081/nexus/content/repositories/releases/</url>
     
should be removed

**Comment by meirwah** [comment]
pending on @hararzafrir  refactor of the nexus build system, right?

**Comment by hararzafrir** [comment]
Yep, will be fixed soon along with the adaptations for Maven Central

**Comment by meirwah** [comment]
this is already fixed @hararzafrir ?

**Comment by hararzafrir** [comment]
Yep
![its-something-meme](https://cloud.githubusercontent.com/assets/5647748/5922728/980060ba-a656-11e4-9615-4d5296da6c3b.png)

**Comment by meirwah** [comment]
FIXED
